### ISSUE TITLE
Theme Generator

### ISSUE THREAD

**Issue by TSenter** [knoxville-utilities-board/nrg-ui#206]
In order to currently generate a theme, a user must clone the repository, modify a file tracked by Git, generate the theme, and copy it out of an untracked directory. Users should not have to leave their current working environment to create/modify themes. Here is a rough guide for what the improved generator should look like:
* A config file (JS) should be read from `.nrg/config.js`. If a config doesn't exist, it should be created.
  * `autoFormat` - if `true`, run Prettier on the generated theme file(s)
  * `outputDir` (required) - the location to save generated CSS to (defaults to `app/styles/themes`)
* A series of theme SCSS files: `.nrg/themes/<name>.scss`
  * Each file specifies a new theme that can be used by setting the `data-theme="<name>"` attribute to any element. The name for the initial theme is `light`.
* CLI commands
  * `build [...name]` - regenerate all (or named) themes
  * `new <name>` - create new theme with name `<name>`

**Comment by KeithClinard** [comment]
Resolved by:
#234 
#241 
#291
